TEAMS_ES = {
    "Argentina": "Argentina",
    "Brazil": "Brasil",
    "Germany": "Alemania",
    "Italy": "Italia",
    "France": "Francia",
    "England": "Inglaterra",
    "Spain": "España",
    "Netherlands": "Países Bajos",
    "Uruguay": "Uruguay",
    "Sweden": "Suecia",
    "Belgium": "Bélgica",
    "Portugal": "Portugal",
    "Croatia": "Croacia",
    "Czechoslovakia": "Checoslovaquia",
    "Hungary": "Hungría",
    "Poland": "Polonia",
    "Austria": "Austria",
    "Switzerland": "Suiza",
    "Chile": "Chile",
    "Denmark": "Dinamarca",
    "Mexico": "México",
    "Japan": "Japón",
    "South Korea": "Corea del Sur",
    "United States": "Estados Unidos",
    "Russia": "Rusia",
    "Serbia": "Serbia",
    "Nigeria": "Nigeria",
    "Cameroon": "Camerún",
    "Morocco": "Marruecos",
    "Senegal": "Senegal",
    "Colombia": "Colombia",
    "Paraguay": "Paraguay",
    "Ghana": "Ghana",
    "Ivory Coast": "Costa de Marfil",
    "Australia": "Australia",
    "Costa Rica": "Costa Rica",
    "Romania": "Rumania",
    "Bulgaria": "Bulgaria",
    "Scotland": "Escocia",
    "Norway": "Noruega",
    "Ireland": "Irlanda",
    "Turkey": "Turquía",
    "Soviet Union": "Unión Soviética",
    "Wales": "Gales",
    "Yugoslavia": "Yugoslavia",
    "Peru": "Perú",
    "Algeria": "Argelia",
    "South Africa": "Sudáfrica",
    "Iran": "Irán",
    "Saudi Arabia": "Arabia Saudita",
    "Tunisia": "Túnez",
    "Ecuador": "Ecuador",
    "Jordan": "Jordania",
    "Ukraine": "Ucrania",
    "New Zealand": "Nueva Zelanda",
    "Canada": "Canadá",
    "Panama": "Panamá",
    "China": "China",
    "Indonesia": "Indonesia",
    "Jamaica": "Jamaica",
    "Slovakia": "Eslovaquia",
    "Angola": "Angola",
    "Mali": "Malí",
    "Iraq": "Irak",
    "Bolivia": "Bolivia",
    "Honduras": "Honduras",
    "Haiti": "Haití",
    "El Salvador": "El Salvador",
    "Zaire": "Zaire",
    "Togo": "Togo",
    "Trinidad and Tobago": "Trinidad y Tobago",
    "United Arab Emirates": "Emiratos Árabes",
    "Kuwait": "Kuwait",
    "Czech Republic": "República Checa",
    "Bosnia": "Bosnia",
    "Slovenia": "Eslovenia",
    "Ethiopia": "Etiopía",
    "Kenya": "Kenia",
    "Greece": "Grecia",
    "Egypt": "Egipto",
    "Russia": "Rusia",
    "Serbia": "Serbia",
    "Czechia": "Chequia",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    "Curaçao": "Curazao",
    "Cabo Verde": "Cabo Verde",
    "Congo DR": "República Dem. del Congo",
    "Uzbekistan": "Uzbekistán",
    "Qatar": "Catar",
}

TEAM_FLAGS = {
    "Argentina": "🇦🇷",
    "Algeria": "🇩🇿",
    "Austria": "🇦🇹",
    "Australia": "🇦🇺",
    "Belgium": "🇧🇪",
    "Bosnia and Herzegovina": "🇧🇦",
    "Brazil": "🇧🇷",
    "Canada": "🇨🇦",
    "Cape Verde": "🇨🇻",
    "Colombia": "🇨🇴",
    "Congo DR": "🇨🇩",
    "Croatia": "🇭🇷",
    "Curacao": "🇨🇼",
    "Curaçao": "🇨🇼",
    "Czechia": "🇨🇿",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Ghana": "🇬🇭",
    "Haiti": "🇭🇹",
    "Iran": "🇮🇷",
    "Iraq": "🇮🇶",
    "Ivory Coast": "🇨🇮",
    "Japan": "🇯🇵",
    "Jordan": "🇯🇴",
    "Mexico": "🇲🇽",
    "Morocco": "🇲🇦",
    "Netherlands": "🇳🇱",
    "New Zealand": "🇳🇿",
    "Norway": "🇳🇴",
    "Panama": "🇵🇦",
    "Paraguay": "🇵🇾",
    "Portugal": "🇵🇹",
    "Qatar": "🇶🇦",
    "Saudi Arabia": "🇸🇦",
    "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Senegal": "🇸🇳",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "Spain": "🇪🇸",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Tunisia": "🇹🇳",
    "Turkey": "🇹🇷",
    "United States": "🇺🇸",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿",
    "Italy": "🇮🇹",
    "Costa Rica": "🇨🇷",
    "Cameroon": "🇨🇲",
    "Denmark": "🇩🇰",
    "Poland": "🇵🇱",
    "Serbia": "🇷🇸",
    "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "Chile": "🇨🇱",
    "Peru": "🇵🇪",
    "Nigeria": "🇳🇬",
    "Russia": "🇷🇺",
    "Hungary": "🇭🇺",
    "Romania": "🇷🇴",
    "Greece": "🇬🇷",
    "Ireland": "🇮🇪",
    "Northern Ireland": "🇬🇧",
    "Slovakia": "🇸🇰",
    "Slovenia": "🇸🇮",
    "Bulgaria": "🇧🇬",
    "Albania": "🇦🇱",
    "North Macedonia": "🇲🇰",
    "Montenegro": "🇲🇪",
    "Iceland": "🇮🇸",
    "Finland": "🇫🇮",
    "Ukraine": "🇺🇦",
    "Belarus": "🇧🇾",
}

STAGES_ES = {
    "Group Stage": "Fase de Grupos",
    "Round of 16": "Octavos de Final",
    "Quarter-finals": "Cuartos de Final",
    "Semi-finals": "Semifinales",
    "Final": "Final",
    "Third place": "Tercer Puesto",
    "Round of 32": "Treintaidosavos",
}

UI_ES = {
    "home_title": "ADIVINAT0R",
    "home_subtitle": "MOTOR DE PREDICCIÓN MUNDIAL 2026",
    "home_hosts": "Anfitriones",
    "home_groups": "Grupos",
    "home_teams": "Equipos",
    "home_phase": "Fase",
    "home_pts": "Pts",
    "home_gf": "GF",
    "home_gc": "GC",
    "home_dg": "DG",
    "home_standing": "CLASIFICACIÓN DE GRUPOS",
    "home_phase_group_stage": "Fase de Grupos",
    "home_next_match": "Próximo Partido",
    "home_no_data": "Simula el torneo para ver resultados",

    "pred_title": "PREDICTOR DE PARTIDOS",
    "pred_desc": "Seleccioná dos equipos y la fase para predecir el resultado",
    "pred_team_a": "EQUIPO A",
    "pred_team_b": "EQUIPO B",
    "pred_vs": "VS",
    "pred_stage": "Fase:",
    "pred_feature_toggles": "Características Activas",
    "pred_run": "EJECUTAR PREDICCIÓN",
    "pred_concentracion": "⚡ ACTIVAR CONCENTRACIÓN MÁXIMA",
    "pred_concentracion_on": "⚡ CONCENTRACIÓN MÁXIMA ACTIVA",
    "pred_score": "Marcador Predicho: --",
    "pred_key_factors": "Factores Clave",
    "pred_active_model": "Modelo Activo",
    "pred_draw": "Empate",
    "pred_confidence": "Confianza",

    "stats_title": "ESTADÍSTICAS DE EQUIPOS",
    "stats_select": "Seleccionar Equipo:",
    "stats_profile": "Perfil Histórico en Mundiales",
    "stats_metrics": "Métricas de Rendimiento",

    "h2h_title": "CARA A CARA",
    "h2h_desc": "Analizá el historial entre dos selecciones",
    "h2h_team_a": "Equipo A",
    "h2h_team_b": "Equipo B",
    "h2h_analyze": "ANALIZAR",
    "h2h_result": "Historial de Enfrentamientos",
    "h2h_date": "Fecha",
    "h2h_tournament": "Torneo",
    "h2h_score": "Marcador",
    "h2h_resultado": "Resultado",
    "h2h_metrics": "Métricas H2H",
    "h2h_total": "Total",
    "h2h_draws": "Empates",
    "h2h_prediction": "Predicción H2H",

    "gen_title": "COMPARADOR DE GENERACIONES",
    "gen_desc": "Explorá las generaciones históricas de cada selección",
    "gen_select": "Seleccionar Equipo:",
    "gen_analyze": "ANALIZAR GENERACIONES",
    "gen_analysis": "Análisis Generacional",
    "gen_generation": "Generación",
    "gen_era": "Época",
    "gen_players": "Jugadores Clave",
    "gen_achievements": "Logros",
    "gen_trends": "Tendencias Generacionales",
    "gen_select_team": "Seleccioná un equipo y presioná ANALIZAR",
    "gen_team": "Equipo:",
    "gen_compare": "Comparar con:",
    "gen_btn": "COMPARAR",
    "gen_current": "Selección Actual",
    "gen_legendary": "Selección Legendaria",
    "gen_rank": "Ranking Histórico",

    "sim_title": "SIMULADOR DEL TORNEO",
    "sim_desc": "Simulación única o Monte Carlo (10,000 simulaciones) para calcular probabilidades",
    "sim_config": "Configuración de Simulación",
    "sim_iterations": "Iteraciones:",
    "sim_run": "EJECUTAR SIMULACIÓN",
    "sim_groups": "Grupos",
    "sim_knockout": "Eliminatorias",
    "sim_stats": "Estadísticas",
    "sim_group": "Grupo",
    "sim_1st": "1°",
    "sim_2nd": "2°",
    "sim_3rd": "3°",
    "sim_4th": "4°",
    "sim_phase": "Fase",
    "sim_fixture": "Partido",
    "sim_result": "Resultado",
    "sim_done": "¡Simulación completa!",
    "sim_single": "Simulación Única",
    "sim_mc": "Monte Carlo (10,000 sims)",
    "sim_mc_ranking": "Probabilidades Monte Carlo",
    "sim_champion": "Campeón del Torneo",

    "cal_title": "CALIBRACIÓN",
    "cal_desc": "Seguimiento de precisión del modelo en tiempo real",
    "cal_metrics": "Métricas de Calibración",
    "cal_accuracy": "Precisión Global",
    "cal_brier": "Puntaje Brier",
    "cal_logloss": "Log Loss",
    "cal_histogram": "Histograma de Confianza",
    "cal_reliability": "Confiabilidad por Rango de Probabilidad",
    "cal_details": "Detalles de Calibración",
    "cal_refresh": "ACTUALIZAR",
    "cal_logged": "predicciones registradas",
    "cal_lower": "menor es mejor",
    "cal_phase": "Precisión por Fase",
    "cal_recent": "Últimas 12 Predicciones",

    "fan_title": "MODO FANTASÍA",
    "fan_desc": "Completá tu bracket y competí contra el motor ADIVINAT0R",
    "fan_budget": "Presupuesto",
    "fan_squad": "Plantel Fantasía",
    "fan_simulate": "SIMULAR PUNTOS",
    "fan_results": "Resultados de la Simulación",
    "fan_no_team": "Presioná SIMULAR PUNTOS para armar tu equipo",
    "fan_points": "Puntos Totales",
    "fan_squad_size": "Jugadores",
    "fan_sim_done": "Simulación completada",
    "fan_champion": "Campeón:",
    "fan_save": "GUARDAR BRACKET",
    "fan_leaderboard": "Tabla de Posiciones",
    "fan_vs_model": "Usuario vs Modelo",

    "alert_upcoming": "📢 Próximos Partidos",
    "alert_no_matches": "No hay partidos próximos. Simulá el torneo para generar el fixture.",
}


def team_es(name_en: str) -> str:
    return TEAMS_ES.get(name_en, name_en)


def team_en(name_es: str) -> str:
    reverse = {v: k for k, v in TEAMS_ES.items()}
    return reverse.get(name_es, name_es)


def stage_es(stage_en: str) -> str:
    return STAGES_ES.get(stage_en, stage_en)


def get_team_list_es() -> list:
    from engine.stats import get_team_list
    return sorted([team_es(t) for t in get_team_list()])


def team_flag(team_en):
    return TEAM_FLAGS.get(team_en, "")


def team_display(team_en):
    flag = TEAM_FLAGS.get(team_en, "")
    es = TEAMS_ES.get(team_en, team_en)
    return f"{flag} {es}"
